substitutions:
  name: yuhui-mppt
  device_description: "Monitor and control a Yuhui MPPT Solar Battery Charger System via RS485"
  external_components_source: github://Depressboy/esphome-yuhui-mppt@main
  tx_pin: GPIO2
  rx_pin: GPIO4
  rx_timeout: 2000ms

esphome:
  name: ${name}
  comment: ${device_description}
  min_version: 2024.6.0
  project:
    name: "Depressboy.esphome-yuhui-mppt"
    version: 1.0.1

esp8266:
  board: d1_mini

external_components:
  - source: ${external_components_source}
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  platform: esphome

logger:
  level: DEBUG

# If you use Home Assistant please remove this `mqtt` section and uncomment the `api` component!
# The native API has many advantages over MQTT: https://esphome.io/components/api.html#advantages-over-mqtt

mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password
  id: mqtt_client

api:

uart:
  - id: uart_bus_0
    baud_rate: 9600
    tx_pin: ${tx_pin}
    rx_pin: ${rx_pin}

custom_modbus:
  - id: mod_0
    uart_id: uart_bus_0

yuhui_mppt:
  - device_address: 1
    id: mppt_0
    custom_modbus_id: mod_0

sensor:
  - platform: yuhui_mppt
    yuhui_mppt_id: mppt_0
    pv_voltage:
      name: PVS-光伏电压
    battery_voltage:
      name: BVS-电池电压
    charging_current:
      name: CCS-充电电流
    internal_temperature:
      name: ITS-内部温度
    external_temperature:
      name: ETS-外部温度
    daily_energy:
      name: DES-日发电量
    total_energy:
      name: TES-总发电量
    charging_power:
      name: CPS-充电功率

switch:
  - platform: yuhui_mppt
    yuhui_mppt_id: mppt_0
    disable_charge_switch:
      name: CHS-禁止充电开关
    dc_output_switch:
      name: DOS-DC输出开关

button:
  - platform: yuhui_mppt
    yuhui_mppt_id: mppt_0
    enable_backlight:
      name: EB-开启背光
    silence_alarm:
      name: SA-消警报声
    clock_calibration:
      name: CC-广播对时

text_sensor:
  - platform: yuhui_mppt
    yuhui_mppt_id: mppt_0
    running_status:
      name: RSS-运行状态
    battery_status:
      name: BSS-电池状态
    fan_status:
      name: FSS-风扇状态
    temperature_status:
      name: TSS-温度状态
    dc_output_status:
      name: DOS-DC输出状态
    internal_temperature1_status:
      name: ITS1-内部温度传感器1
    internal_temperature2_status:
      name: ITS2-内部温度传感器2
    external_temperature1_status:
      name: ETS-外部温度传感器

binary_sensor:
  - platform: yuhui_mppt
    yuhui_mppt_id: mppt_0
    charging_status:
      name: CHS-充电状态
    equalizing_charge:
      name: ECS-均衡充电
    tracking:
      name: TKS-追踪充电
    floating_charge:
      name: FCH-浮充状态
    charging_current_limit:
      name: CCL-充电限流
    charging_derating:
      name: CDS-充电降额
    remote_control_disable_charging:
      name: RCD-远程禁止充电
    pv_overvoltage:
      name: POS-PV过压
    charging_relay:
      name: CRS-充电输出继电器
    load_output:
      name: LOS-负载输出
    fan_control:
      name: FCS-风扇开启
    overcharge_protection:
      name: OCP-过充保护
    overvoltage_protection:
      name: OVP-过压保护

time:
  - platform: sntp
    id: my_time 
